"""empty message

Revision ID: 023f3c26de91
Revises: 5d1439b6cba3
Create Date: 2020-08-17 14:21:13.233241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023f3c26de91'
down_revision = '5d1439b6cba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('bill_amount', sa.Float(precision=2), nullable=False))
    op.add_column('bills', sa.Column('bill_due_date', sa.Date(), nullable=True))
    op.add_column('bills', sa.Column('bill_name', sa.String(length=20), nullable=False))
    op.drop_column('bills', 'due_date')
    op.drop_column('bills', 'amount')
    op.drop_column('bills', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('bills', sa.Column('amount', sa.REAL(), autoincrement=False, nullable=False))
    op.add_column('bills', sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('bills', 'bill_name')
    op.drop_column('bills', 'bill_due_date')
    op.drop_column('bills', 'bill_amount')
    # ### end Alembic commands ###
