"""empty message

Revision ID: 02b1209a0900
Revises: ad8fb941343d
Create Date: 2020-08-21 00:59:47.387463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b1209a0900'
down_revision = 'ad8fb941343d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paychecks', sa.Column('exemptions', sa.Integer(), nullable=False))
    op.add_column('paychecks', sa.Column('filing_status', sa.Text(), nullable=False))
    op.add_column('paychecks', sa.Column('pay_frequency', sa.Text(), nullable=False))
    op.add_column('paychecks', sa.Column('state', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paychecks', 'state')
    op.drop_column('paychecks', 'pay_frequency')
    op.drop_column('paychecks', 'filing_status')
    op.drop_column('paychecks', 'exemptions')
    # ### end Alembic commands ###
