"""empty message

Revision ID: 145df4f73ca2
Revises: 22527c758991
Create Date: 2020-08-17 19:12:58.148706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145df4f73ca2'
down_revision = '22527c758991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings_goal', sa.Column('previous_amount', sa.Float(precision=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savings_goal', 'previous_amount')
    # ### end Alembic commands ###
