"""empty message

Revision ID: 23d475820afb
Revises: 02b1209a0900
Create Date: 2020-08-21 01:04:02.025516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d475820afb'
down_revision = '02b1209a0900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paychecks', sa.Column('federal_taxes', sa.Float(precision=2), nullable=False))
    op.add_column('paychecks', sa.Column('fica_taxes', sa.Float(precision=2), nullable=False))
    op.add_column('paychecks', sa.Column('state_taxes', sa.Float(precision=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paychecks', 'state_taxes')
    op.drop_column('paychecks', 'fica_taxes')
    op.drop_column('paychecks', 'federal_taxes')
    # ### end Alembic commands ###
