"""empty message

Revision ID: 320cb4fe473c
Revises: 12c2041900ba
Create Date: 2020-08-20 14:33:07.142031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320cb4fe473c'
down_revision = '12c2041900ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savings_goals', 'current_savings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings_goals', sa.Column('current_savings', sa.REAL(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
