"""empty message

Revision ID: 426bdb0ef654
Revises: bf3cf2275ff8
Create Date: 2020-08-13 22:39:56.452146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426bdb0ef654'
down_revision = 'bf3cf2275ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paychecks', 'pay_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paychecks', 'pay_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
