"""empty message

Revision ID: 5f783c12ff94
Revises: 23d475820afb
Create Date: 2020-08-21 01:31:16.012578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f783c12ff94'
down_revision = '23d475820afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paychecks', sa.Column('pre_tax_deductions', sa.Float(precision=2), nullable=True))
    op.add_column('paychecks', sa.Column('total_deductions', sa.Float(precision=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paychecks', 'total_deductions')
    op.drop_column('paychecks', 'pre_tax_deductions')
    # ### end Alembic commands ###
