"""empty message

Revision ID: 5fb6ce3bf7dc
Revises: 8e0b5b23021f
Create Date: 2020-08-23 16:44:45.853707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb6ce3bf7dc'
down_revision = '8e0b5b23021f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
