"""empty message

Revision ID: 66095246c816
Revises: 
Create Date: 2020-08-10 13:37:40.611960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66095246c816'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a_table_name',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('second_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('second_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='second_table_pkey')
    )
    op.drop_table('a_table_name')
    # ### end Alembic commands ###
