"""empty message

Revision ID: 6c7ea29788a5
Revises: 33c95d2167b1
Create Date: 2020-08-19 20:06:00.603486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7ea29788a5'
down_revision = '33c95d2167b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('savings_entries', 'amount',
               existing_type=sa.REAL(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('savings_entries', 'amount',
               existing_type=sa.REAL(),
               nullable=False)
    # ### end Alembic commands ###
