"""empty message

Revision ID: 894e5af08304
Revises: feb7ea7ac2cd
Create Date: 2020-08-17 19:46:31.228491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894e5af08304'
down_revision = 'feb7ea7ac2cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('savings_entry', 'total',
               existing_type=sa.REAL(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('savings_entry', 'total',
               existing_type=sa.REAL(),
               nullable=False)
    # ### end Alembic commands ###
