"""empty message

Revision ID: 8f2ac6d49a49
Revises: 466c857ce605
Create Date: 2020-08-22 13:21:43.598571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f2ac6d49a49'
down_revision = '466c857ce605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paychecks',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('pay_frequency', sa.Text(), nullable=False),
    sa.Column('filing_status', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('exemptions', sa.Integer(), nullable=False),
    sa.Column('gross_pay', sa.Float(precision=2), nullable=False),
    sa.Column('pre_tax_deductions', sa.Float(precision=2), nullable=True),
    sa.Column('federal_taxes', sa.Float(precision=2), nullable=False),
    sa.Column('state_taxes', sa.Float(precision=2), nullable=False),
    sa.Column('fica_taxes', sa.Float(precision=2), nullable=False),
    sa.Column('total_deductions', sa.Float(precision=2), nullable=False),
    sa.Column('net', sa.Float(precision=2), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paychecks')
    # ### end Alembic commands ###
