"""empty message

Revision ID: 93c237a79bfd
Revises: 894e5af08304
Create Date: 2020-08-18 14:55:10.227493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93c237a79bfd'
down_revision = '894e5af08304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_entries',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('savings_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Float(precision=2), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('total_savings_log',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('total', sa.Float(precision=2), nullable=False),
    sa.Column('savings_id', postgresql.UUID(), nullable=True),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['savings_id'], ['savings_entries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('savings_goals',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(precision=2), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.Column('savings_total_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['savings_total_id'], ['total_savings_log.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('savings_goal')
    op.drop_table('savings_entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_entry',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('savings_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('amount', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('total', sa.REAL(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='savings_entry_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='savings_entry_pkey')
    )
    op.create_table('savings_goal',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('previous_amount', sa.REAL(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='savings_goal_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='savings_goal_pkey')
    )
    op.drop_table('savings_goals')
    op.drop_table('total_savings_log')
    op.drop_table('savings_entries')
    # ### end Alembic commands ###
