"""empty message

Revision ID: ad8fb941343d
Revises: 320cb4fe473c
Create Date: 2020-08-21 00:58:47.734885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8fb941343d'
down_revision = '320cb4fe473c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paychecks', sa.Column('exemptions', sa.Integer(), nullable=False))
    op.add_column('paychecks', sa.Column('filing_status', sa.Text(), nullable=False))
    op.add_column('paychecks', sa.Column('pay_frequency', sa.Text(), nullable=False))
    op.add_column('paychecks', sa.Column('state', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paychecks', 'state')
    op.drop_column('paychecks', 'pay_frequency')
    op.drop_column('paychecks', 'filing_status')
    op.drop_column('paychecks', 'exemptions')
    # ### end Alembic commands ###
