"""empty message

Revision ID: bdd283763bd2
Revises: 8e8eb74383a3
Create Date: 2020-08-21 16:27:01.269907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd283763bd2'
down_revision = '8e8eb74383a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('is_paid', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'is_paid')
    # ### end Alembic commands ###
