"""empty message

Revision ID: e1f66c930498
Revises: b9bc333ebd73
Create Date: 2020-08-26 15:14:36.867520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f66c930498'
down_revision = 'b9bc333ebd73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paychecks', 'exemptions',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paychecks', 'exemptions',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
