"""empty message

Revision ID: f81b763f156d
Revises: baa58f0aec36
Create Date: 2020-08-23 16:05:54.712983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f81b763f156d'
down_revision = 'baa58f0aec36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bills',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('bill_name', sa.String(length=20), nullable=False),
    sa.Column('bill_due_date', sa.Date(), nullable=True),
    sa.Column('bill_amount', sa.Float(precision=2), nullable=False),
    sa.Column('is_paid', sa.Text(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'paychecks', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'savings_entries', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'savings_goals', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'total_savings_log', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'total_savings_log', type_='foreignkey')
    op.drop_constraint(None, 'savings_goals', type_='foreignkey')
    op.drop_constraint(None, 'savings_entries', type_='foreignkey')
    op.drop_constraint(None, 'paychecks', type_='foreignkey')
    op.drop_table('bills')
    op.drop_table('users')
    # ### end Alembic commands ###
