"""empty message

Revision ID: feb7ea7ac2cd
Revises: 145df4f73ca2
Create Date: 2020-08-17 19:35:28.621368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb7ea7ac2cd'
down_revision = '145df4f73ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings_entry', sa.Column('total', sa.Float(precision=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savings_entry', 'total')
    # ### end Alembic commands ###
